title: Leaf Blog
iconURL: assets/default-icon.png
theme: jekyll-theme-leaf

# for a clean URL
permalink: :slug

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-remote-theme

remote_theme: supun-io/jekyll-theme-leaf
