title: "KPTBS Selbsthilfegruppe Online & Berlin (Komplexe Posttraumatische Belastungsstörung)"
short_title: KPTBS Selbsthilfe
iconURL: assets/kptbs-icon.png
logo: assets/kptbs-icon.png
remote_theme: 3xz/k-ptbs
url: https://k-ptbs.com
baseurl: /

# for a clean URL
permalink: :slug

social:
  instagram: kptbs.selbsthilfe
  facebook: kptbs.selbsthilfe
  links:
    - https://instagram.com/kptbs.selbsthilfe
    - https://facebook.com/kptbs.selbsthilfe

plugins:
 - jekyll-seo-tag
 - jekyll-remote-theme
 - jekyll-feed
